# Generated by Django 5.0.14 on 2026-08-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trialing', max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='tenants_ten_status_e7eaee_idx')],
            },
        ),
    ]
